basePath: /notifications/api
definitions:
  CoreUserRef:
    properties:
      name:
        type: string
      uid:
        type: string
    type: object
  Recipient:
    properties:
      name:
        type: string
      user_id:
        type: string
    type: object
  Topic:
    properties:
      date_created:
        type: string
      date_updated:
        type: string
      description:
        type: string
      name:
        type: string
    type: object
  getMessagesRequestBody:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
  model.Message:
    properties:
      body:
        type: string
      data:
        additionalProperties:
          type: string
        type: object
      date_created:
        type: string
      date_updated:
        type: string
      id:
        type: string
      priority:
        type: integer
      recipients:
        items:
          $ref: '#/definitions/Recipient'
        type: array
      sender:
        $ref: '#/definitions/model.Sender'
      subject:
        type: string
      topic:
        type: string
    type: object
  model.Sender:
    properties:
      type:
        description: user or system
        type: string
      user:
        $ref: '#/definitions/CoreUserRef'
    type: object
  storeTokenBody:
    properties:
      previous_token:
        type: string
      token:
        type: string
    type: object
host: localhost
info:
  contact: {}
  description: Rokwire Notifications Building Block API Documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Rokwire Notifications Building Block API
  version: 0.1.9
paths:
  /admin/message:
    post:
      consumes:
      - application/json
      description: Creates a message
      operationId: CreateMessage
      parameters:
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Message'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
      security:
      - AdminUserAuth: []
      tags:
      - Admin
    put:
      consumes:
      - application/json
      description: Updates a message
      operationId: UpdateMessage
      parameters:
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Message'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
      security:
      - AdminUserAuth: []
      tags:
      - Admin
  /admin/message/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a message with id
      operationId: DeleteMessage
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      security:
      - AdminUserAuth: []
      tags:
      - Admin
    get:
      consumes:
      - application/json
      description: Retrieves a message by id
      operationId: GetMessage
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
      security:
      - AdminUserAuth: []
      tags:
      - Admin
  /admin/messages:
    get:
      description: Gets all messages
      operationId: GetMessages
      parameters:
      - description: user - filter by user
        in: query
        name: user
        type: string
      - description: topic - filter by topic
        in: query
        name: topic
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      - description: limit - limit the result
        in: query
        name: limit
        type: string
      - description: 'order - Possible values: asc, desc. Default: desc'
        in: query
        name: order
        type: string
      - description: start_date - Start date filter in milliseconds as an integer
          epoch value
        in: query
        name: start_date
        type: string
      - description: end_date - End date filter in milliseconds as an integer epoch
          value
        in: query
        name: end_date
        type: string
      security:
      - AdminUserAuth: []
      tags:
      - Admin
  /admin/topic:
    put:
      description: Updated the topic.
      operationId: UpdateTopic
      parameters:
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/Topic'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Topic'
      security:
      - AdminUserAuth: []
      tags:
      - Admin
  /admin/topics:
    get:
      description: Gets all topics
      operationId: AdminGetTopics
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Topic'
            type: array
      security:
      - AdminUserAuth: []
      tags:
      - Admin
  /int/message:
    post:
      description: Sends a message to a user, list of users or a topic
      operationId: InternalSendMessage
      parameters:
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Message'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
      security:
      - InternalAuth: []
      tags:
      - Internal
  /message:
    post:
      consumes:
      - application/json
      description: Creates a message
      operationId: createMessage
      parameters:
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Message'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
      security:
      - UserAuth: []
      tags:
      - Client
  /message/{id}:
    delete:
      description: Removes the current user from the recipient list of the message
      operationId: DeleteUserMessage
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    get:
      consumes:
      - application/json
      description: Retrieves a message by id
      operationId: GetUserMessage
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Message'
      security:
      - UserAuth: []
      tags:
      - Client
  /messages:
    delete:
      consumes:
      - application/json
      description: Removes the current user from the recipient list of all described
        messages
      operationId: DeleteUserMessages
      parameters:
      - description: body json of the all message ids that need to be filtered
        in: body
        name: data
        schema:
          $ref: '#/definitions/getMessagesRequestBody'
      responses:
        "200":
          description: ""
      security:
      - UserAuth: []
      tags:
      - Client
    get:
      consumes:
      - application/json
      description: Gets all messages to the authenticated user.
      operationId: GetUserMessages
      parameters:
      - description: offset
        in: query
        name: offset
        type: string
      - description: limit - limit the result
        in: query
        name: limit
        type: string
      - description: 'order - Possible values: asc, desc. Default: desc'
        in: query
        name: order
        type: string
      - description: start_date - Start date filter in milliseconds as an integer
          epoch value
        in: query
        name: start_date
        type: string
      - description: end_date - End date filter in milliseconds as an integer epoch
          value
        in: query
        name: end_date
        type: string
      - description: body json of the all message ids that need to be filtered
        in: body
        name: data
        schema:
          $ref: '#/definitions/getMessagesRequestBody'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Message'
            type: array
      security:
      - UserAuth: []
      tags:
      - Client
  /token:
    post:
      consumes:
      - application/json
      description: Stores a firebase token and maps it to a idToken if presents
      operationId: Token
      parameters:
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/storeTokenBody'
      responses:
        "200":
          description: ""
      security:
      - RokwireAuth UserAuth: []
      tags:
      - Client
  /topic/{topic}/messages:
    get:
      description: Gets all messages for topic
      operationId: GetTopicMessages
      parameters:
      - description: topic
        in: path
        name: topic
        required: true
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      - description: limit - limit the result
        in: query
        name: limit
        type: string
      - description: 'order - Possible values: asc, desc. Default: desc'
        in: query
        name: order
        type: string
      - description: start_date - Start date filter in milliseconds as an integer
          epoch value
        in: query
        name: start_date
        type: string
      - description: end_date - End date filter in milliseconds as an integer epoch
          value
        in: query
        name: end_date
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Message'
            type: array
      security:
      - RokwireAuth UserAuth: []
      tags:
      - Client
  /topic/{topic}/subscribe:
    post:
      consumes:
      - application/json
      description: Subscribes the current user to a topic
      operationId: Subscribe
      parameters:
      - description: topic
        in: path
        name: topic
        required: true
        type: string
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/storeTokenBody'
      responses:
        "200":
          description: ""
      security:
      - RokwireAuth UserAuth: []
      tags:
      - Client
  /topic/{topic}/unsubscribe:
    post:
      description: Unsubscribes the current user to a topic
      operationId: Unsubscribe
      parameters:
      - description: topic
        in: path
        name: topic
        required: true
        type: string
      - description: body json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/storeTokenBody'
      responses:
        "200":
          description: ""
      security:
      - RokwireAuth UserAuth: []
      tags:
      - Client
  /topics:
    get:
      description: Gets all topics
      operationId: GetTopics
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Topic'
            type: array
      security:
      - RokwireAuth: []
      tags:
      - Client
  /version:
    get:
      description: Gives the service version.
      operationId: Version
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      security:
      - RokwireAuth: []
      tags:
      - Client
schemes:
- https
securityDefinitions:
  AdminUserAuth:
    in: header (add admin id token with Bearer prefix to the Authorization value)
    name: Authorization
    type: apiKey
  InternalAuth:
    in: header
    name: INTERNAL-API-KEY
    type: apiKey
  RokwireAuth:
    in: header
    name: ROKWIRE-API-KEY
    type: apiKey
  UserAuth:
    in: header (add client id token with Bearer prefix to the Authorization value)
    name: Authorization
    type: apiKey
swagger: "2.0"
